# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Computer Science
author: Duraraijan, Norris, and Young
logo: logo.png

# Trying to integrate Thebe
# Taken directly from https://jupyterbook.org/interactive/launchbuttons.html#launchbuttons-configuration
launch_buttons:
  thebe: true
  notebook_interface: "classic"  # or "jupyterlab"
  binderhub_url: "https://mybinder.org"
  # binderhub_url:  http://localhost:12000  # The URL for your BinderHub
  url                       : https://github.com/UO-CIS-OER/sample-jupybook 
  path_to_book              : IntroCS 
  branch                    : main  

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
repository:
  url:  https://github.com/UO-CIS-OER/sample-jupybook 
html:
  use_issues_button: true
  use_repository_button: true

# See https://jupyterbook.org/file-types/jupytext.html for format choice
sphinx:
  config:
    nb_custom_formats:
         .pmd:
            - jupytext.reads
            - fmt: percent
